server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**,/api/auth/**
        - id: employee_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/employees/**

eureka:
  client:
    enabled: false
