server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user_service
          uri: lb://user_service
          predicates:
            - Path=/api/users/**,/api/auth/**
        - id: employee_service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
